#!/bin/bash
# ============================================================================
# 3CX SBC Docker Entrypoint
# ============================================================================
# Configures and starts the 3CX Session Border Controller.
# Supports two modes:
#   auto (default): configure via environment variables
#   prov: mount a .prov file from 3CX Management Console
# ============================================================================

set -e

CONFIG_DIR="/etc/3cxsbc"
SBC_BINARY="/usr/sbin/3cxsbc"

# ---- Provision from env vars ----
if [ "$SBC_MODE" = "auto" ] || [ "$SBC_MODE" = "" ]; then
    if [ -n "$SBC_FQDN" ] && [ -n "$SBC_AUTH_ID" ] && [ -n "$SBC_PASSWORD" ]; then
        echo "[SBC] Configuring from environment variables..."
        echo "[SBC]   FQDN: $SBC_FQDN"
        echo "[SBC]   Name: ${SBC_NAME:-auto-generated}"
        echo "[SBC]   LAN IP: ${SBC_LAN_IP:-auto}"

        # Generate provisioning from env vars
        # 3CX SBC reads config from /etc/3cxsbc/sbc.conf or similar.
        # The exact config format depends on the SBC version.
        # We write the provisioning key env vars for the SBC to pick up
        cat > /etc/default/3cxsbc <<EOF
# Generated by Docker entrypoint
SBC_FQDN=${SBC_FQDN}
SBC_AUTH_ID=${SBC_AUTH_ID}
SBC_PASSWORD=${SBC_PASSWORD}
SBC_NAME=${SBC_NAME:-docker-sbc}
SBC_LAN_IP=${SBC_LAN_IP:-auto}
EOF

        # Run the SBC config helper (creates the .prov from env vars)
        if command -v 3cxsbc-config &> /dev/null; then
            3cxsbc-config \
                --fqdn "$SBC_FQDN" \
                --auth-id "$SBC_AUTH_ID" \
                --password "$SBC_PASSWORD" \
                ${SBC_NAME:+--name "$SBC_NAME"} \
                ${SBC_LAN_IP:+--lan-ip "$SBC_LAN_IP"} \
                --non-interactive
        fi

        echo "[SBC] Configuration written."
    else
        echo "[SBC] WARNING: SBC_MODE=auto but SBC_FQDN, SBC_AUTH_ID, and SBC_PASSWORD not all set."
        echo "[SBC] Starting with minimal config (will need manual provisioning)."
    fi
fi

# ---- Provision from mounted .prov file ----
if [ "$SBC_MODE" = "prov" ]; then
    if [ -f "$CONFIG_DIR/3cxsbc.prov" ]; then
        echo "[SBC] Using provisioning file: $CONFIG_DIR/3cxsbc.prov"
    else
        echo "[SBC] ERROR: SBC_MODE=prov but no provisioning file found at $CONFIG_DIR/3cxsbc.prov"
        echo "[SBC] Mount your .prov file: -v /path/to/your.prov:$CONFIG_DIR/3cxsbc.prov"
        exit 1
    fi
fi

# ---- Start the SBC ----
echo "[SBC] Starting 3CX SBC..."
echo "[SBC] Binary: $SBC_BINARY"

if [ -f "$SBC_BINARY" ]; then
    exec "$SBC_BINARY"
else
    echo "[SBC] ERROR: SBC binary not found at $SBC_BINARY"
    echo "[SBC] The 3cxsbc package may not be installed correctly."
    exit 1
fi
